name: CI

on:
  push:
  pull_request:

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Django tests
        env:
          DJANGO_SETTINGS_MODULE: config.settings.dev
        run: |
          python manage.py migrate --noinput
          python manage.py test -v 2

      - name: Ruff
        run: |
          pip install ruff
          ruff check .

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: ESLint
        run: |
          npm ci || npm install
          npx eslint portfolio/static/portfolio/js --ext .js